### ISSUE TITLE
Conflict Issues

### ISSUE THREAD

**Issue by kerry407** [chukaibejih/smart_learn#11]
@chukaibejih What service are you working on?

**Comment by chukaibejih** [comment]
I haven't started yet but from the ER Diagram, I intend to start maybe lessons or module.

 I see you have conflict issues, have "git pull" before pushing?

**Comment by kerry407** [comment]
I have solved the conflicts. I have started modelling the course_service. I added an extra field "cover_image" which is not in the ER diagram for course.

**Comment by kerry407** [comment]
![Screenshot (297)](https://user-images.githubusercontent.com/63162639/228085420-54a61b33-4c2e-4c9f-8e14-2685eaa55734.png)
I keep getting this error while migrating
