### ISSUE TITLE
Suggestion to create a new endpoint that will be the details of a user but with only public details

### ISSUE THREAD

**Issue by mayals** [chukaibejih/smart_learn#112]
The profile page is the personal page that viewed only by the request user (the owner of this page) because it might contain Personal and sensitive information about himself, so only this user has the full permission to view and partial update of his own data.
By the other hand, some information in this profile page might have considered as a public information of this user, so the idea of Suggestion is to create a new endpoint that will be the details of a user but with only public profile information,this endpoint can retrieve by(user_id).

**Comment by chukaibejih** [comment]
Thank you for raising this issue and providing your suggestion. It's a valuable point you've made regarding the profile page and the sensitivity of personal information. I agree that having a separate endpoint for retrieving only public profile information is a good idea.

Considering the importance of this feature, I wanted to ask if you would be interested in working on it?

**Comment by mayals** [comment]
Yes of course, i will do it.
