### ISSUE TITLE
for some reason i couldn't get the confirmation mail

### ISSUE THREAD

**Issue by AkshayaPujitha** [chukaibejih/smart_learn#115]

**Comment by chukaibejih** [comment]
Hello Pujitha, did you check the terminal? The API is currently using the console email backend.

**Comment by chukaibejih** [comment]
> > Hello Pujitha, did you check the terminal? The API is currently using the console email backend.
> 
> yeah but needed to verify from actual email isn't it??

If an email service is set up, then indeed, you should receive the confirmation in your inbox. However, since we currently have the email backend configured as console, the confirmation will be displayed in your terminal.

**Comment by AkshayaPujitha** [comment]
> > > Hello Pujitha, did you check the terminal? The API is currently using the console email backend.
> > 
> > 
> > yeah but needed to verify from actual email isn't it??
> 
> If an email service is set up, then indeed, you should receive the confirmation in your inbox. However, since we currently have the email backend configured as console, the confirmation will be displayed in your terminal.

Yes, I understand... I assumed that since you're using Twilio for phone number verification, we could also use it for email, right?

**Comment by chukaibejih** [comment]
> 



> > > > Hello Pujitha, did you check the terminal? The API is currently using the console email backend.
> > > 
> > > 
> > > yeah but needed to verify from actual email isn't it??
> > 
> > 
> > If an email service is set up, then indeed, you should receive the confirmation in your inbox. However, since we currently have the email backend configured as console, the confirmation will be displayed in your terminal.
> 
> Yes, I understand... I assumed that since you're using Twilio for phone number verification, we could also use it for email, right?

Absolutely, your assumption is reasonable. However, currently, we have the email verification process set up differently from the phone number verification. While Twilio is handling phone number verification, we're using a separate approach for email confirmation.

**Comment by AkshayaPujitha** [comment]
> > 
> 
> > > > > Hello Pujitha, did you check the terminal? The API is currently using the console email backend.
> > > > 
> > > > 
> > > > yeah but needed to verify from actual email isn't it??
> > > 
> > > 
> > > If an email service is set up, then indeed, you should receive the confirmation in your inbox. However, since we currently have the email backend configured as console, the confirmation will be displayed in your terminal.
> > 
> > 
> > Yes, I understand... I assumed that since you're using Twilio for phone number verification, we could also use it for email, right?
> 
> Absolutely, your assumption is reasonable. However, currently, we have the email verification process set up differently from the phone number verification. While Twilio is handling phone number verification, we're using a separate approach for email confirmation.

oh okay.
