### ISSUE TITLE
Error while trying to log in

### ISSUE THREAD

**Issue by kerry407** [chukaibejih/smart_learn#13]
![Screenshot (300)](https://user-images.githubusercontent.com/63162639/228334880-242827eb-8a5c-48d8-b0fa-402721c46981.png)
In user_service.views.CustomTokenObtainPairViewSet

**Comment by chukaibejih** [comment]
1. In your virtual environment folder, inside lib look for jwt/algorithm.py 

2. You'll see Class HMAC Algorithm

3. check for the function prepare_key(self, key)

4. Edit the next line to key = force_byte(str(key). 


For better understanding of what happened here, I worte it here [https://twitter.com/_ibejih/status/1638209713782370307?s=19]()

**Comment by kerry407** [comment]
Okay, It has resolved

**Comment by chukaibejih** [comment]
> Okay, It has resolved

Awesome!
