### ISSUE TITLE
No Review in ER Diagram

### ISSUE THREAD

**Issue by kerry407** [chukaibejih/smart_learn#14]
The Review field in Course which is int doesn't have a model in the ER diagram. We should create One. 
{
  "user": user__uuid,
  "review_body": varchar,
  "rating":  int,
  "course": course__uuid
}

**Comment by kerry407** [comment]
We  could also add a new field "rating" in the Course Model to connect it to the rating field in Review model

**Comment by chukaibejih** [comment]
Do you an account on dbdiagram.io?

**Comment by kerry407** [comment]
No I don’t

**Comment by chukaibejih** [comment]
The Review model has been added to the ER Diagram, you can have a look and close the issue.
