### ISSUE TITLE
Solving Slow Queries by Eliminating the N+1 Query Problem in the API 

### ISSUE THREAD

**Issue by chukaibejih** [chukaibejih/smart_learn#15]
We need to take care of the N+1 query problem, where we are making N queries to retrieve N-related objects, resulting in a significant amount of extra queries and slowing down the overall performance of our API.

**Comment by chukaibejih** [comment]
> We need to take care of the N+1 query problem, where we are making N queries to retrieve N-related objects, resulting in a significant amount of extra queries and slowing down the overall performance of our API.

I am working on it.

**Comment by kerry407** [comment]
Send a screenshot of where this occurs

**Comment by chukaibejih** [comment]
Using the GET `courses/course/` endpoint for example. This is before and after resolving the N + 1 query problem. Check the number of queries and the time. 

![twii](https://user-images.githubusercontent.com/29266211/229286446-67331f87-0783-454b-8e7a-47344af1ba00.png)
![twii2](https://user-images.githubusercontent.com/29266211/229286452-5414c707-7d98-4c5d-b23b-8060dc224e14.png)

**Comment by kerry407** [comment]
I can't see a change in the query, what is the change in the query code, let me compare

**Comment by chukaibejih** [comment]
The first screen ran 4 queries in 45.00 ms while the second ran 3 queries in 17.01 ms

**Comment by kerry407** [comment]
Okay you used select_related or prefetch_related
