### ISSUE TITLE
Make course difficulty an Enum 

### ISSUE THREAD

**Issue by chukaibejih** [chukaibejih/smart_learn#24]
Make the course difficulty an Enum/Choices instead of a positive interger. 
![image](https://user-images.githubusercontent.com/29266211/231100063-571f4233-d6ca-4f74-ad2c-bf3918067309.png)

**Comment by kerry407** [comment]
Okay

**Comment by kerry407** [comment]
done
![Screenshot (382)](https://user-images.githubusercontent.com/63162639/231307446-4b65b0a7-1f5b-46bb-a47c-c0800225011c.png)

**Comment by chukaibejih** [comment]
Nice one 👏🏾

**Comment by chukaibejih** [comment]
I think having them in all caps is an over kill. "Beginner, Intermediate, Advanced" looks better

**Comment by kerry407** [comment]
done
