### ISSUE TITLE
Some of the test cases for course service failed. 

### ISSUE THREAD

**Issue by chukaibejih** [chukaibejih/smart_learn#31]
Two test cases for the course service failed. Could you please have a look at it whenever you can? @kerry407 
![image](https://user-images.githubusercontent.com/29266211/233307011-40cfe88c-9431-42a6-8be0-6d19dcc9a445.png)

**Comment by kerry407** [comment]
Yeah, Because I changed difficulty to enums. I have fixed it tho

**Comment by chukaibejih** [comment]
Oh okay. Nice one 👏🏾
