### ISSUE TITLE
No .env file example in project

### ISSUE THREAD

**Issue by Benji918** [chukaibejih/smart_learn#44]
**No .env file example**
Not have an example of what a typical developer should have in his/her .env file for this project in neither the repo or the readme file makes contributing to your work alot harder.
I applead to you to please fix this🤲

**Comment by chukaibejih** [comment]
Thank you for bringing this issue to my attention. I understand how having a missing .env file example can make contributing to the project more challenging. I will create a .env template in the root directory.

**Comment by chukaibejih** [comment]
This has been done. You can close the issue.

**Comment by Benji918** [comment]
Thanks 😊
