### ISSUE TITLE
Request to Add PageNumberPagination to UserViewSet API

### ISSUE THREAD

**Issue by easonliao1994** [chukaibejih/smart_learn#52]
I would like to request the addition of PageNumberPagination to the UserViewSet API in order to improve the pagination of user data.

Currently, the API returns all users in a single response, which may lead to performance issues when the number of users is large. By incorporating PageNumberPagination, we can limit the number of users returned per page and provide pagination links for easier navigation through the user data.

I propose the following changes to the UserViewSet:

```
from rest_framework.pagination import PageNumberPagination
class UserViewSet(AutoPrefetchViewSetMixin, viewsets.ModelViewSet):
    # ...

    # Set the pagination class and page_size
    pagination_class = PageNumberPagination
    page_size = 20
    
    # ...
```

By implementing pagination, we can enhance the API's performance and provide a more user-friendly experience when dealing with a large number of users.

I appreciate your consideration of this feature request. Please let me know if you have any questions or if there is any additional information I can provide to support this proposal.

Thank you!

**Comment by chukaibejih** [comment]
You can go ahead and implement pagination to the UserViewSet.
