### ISSUE TITLE
Add Contribution Guidelines

### ISSUE THREAD

**Issue by chukaibejih** [chukaibejih/smart_learn#95]
Include clear contribution guidelines in the project's documentation to provide guidance to potential contributors. This will encourage collaboration and streamline the process of accepting contributions.

**Comment by Tholkappiar** [comment]
Hello [chukaibejih](https://github.com/chukaibejih) , 

Could please provide more information about the guidelines what are guidelines which are must needed and important for this repository and also where (location) can i make the contribution guidelines file like by creating a new CONTRIBUTING.md or by some other ways .

Thanks,
Tholkappiar

**Comment by chukaibejih** [comment]
Hello Tholkappiar,

Thank you for your interest in contributing to the Smart Learning API repository. I appreciate it. Regarding your questions, You can add the CONTRIBUTING.md file to the root directory of the repository.

- Introduction: A brief introduction to the repository and its purpose. You can pick this from the README

- Getting Started: Instructions on how to set up the development environment and run the API locally. You can also pick this from the README

- Code of Conduct:  I do not think it is a MUST 

- Contributing Process: Step-by-step instructions on how to contribute, including forking the repository, creating a new branch, making changes, and submitting a pull request.

- Coding Guidelines: Instructions on coding conventions, style, and best practices. Such as Using consistent indentation (4 spaces) and following the PEP 8 style guide for Python code., Write clear and meaningful variable and function names., Include comments where necessary to improve code readability., Follow best practices and apply common software engineering principles.

- Testing: Guidance on writing tests and running them successfully. (Important) - We highly encourage writing tests for any new features or bug fixes. Tests help ensure the stability and reliability of the API.

- Documentation: The importance of maintaining clear and comprehensive documentation, including updating the README.md file and docstrings.

- Issue and Discussion: Instructions on how to report bugs, ask questions, and suggest improvements. If someone encounters a bug, has a question, or wants to suggest an improvement, should create a new issue in the repository. Make sure to provide a clear description and, if applicable, steps to reproduce the issue.

For now, I think these are the major things but feel free to make any necessary changes. If you have any further questions or need additional assistance, please let me know.

Cheers.
