### ISSUE TITLE
Add Endpoint to Retrieve Enrolled Users

### ISSUE THREAD

**Issue by chukaibejih** [chukaibejih/smart_learn#98]
Currently, the API lacks an endpoint to retrieve information about users who have enrolled in a course. This functionality is important for instructors to track and manage their course enrollments effectively. We need to add an API endpoint that allows instructors to view the list of enrolled users for a specific course.

The new endpoint should provide instructors with essential details about each enrolled user, such as their username, email address, enrollment date, and progress within the course. This information will enable instructors to monitor the course's popularity, track user engagement, and tailor their teaching strategies accordingly.

It would be helpful to include filtering and pagination options in the endpoint to handle large numbers of enrolled users efficiently. Instructors should be able to filter users based on criteria such as enrollment date, completion status, or quiz scores.

**Comment by JohnCarlSalao** [comment]
Can I work with this one?

**Comment by chukaibejih** [comment]
Hello John, yes you can work on this issue. You can go through the readme and contribution guidelines to get started.
